---
cluster_name: "do-sample"
cluster_region: "nyc1"
prefix_version: "1.22."
node_pool_default:
  name: do-sample-node-pool
  size: s-2vcpu-2gb
  node_count: "1"
additional_node_pools: {}
users_list:
  - name: root-user
    role: root
tags: ["VKPR", "k8s-digitalocean"]
